# Generated by Django 3.2.3 on 2021-06-01 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paints', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='paint',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='paints.paint'),
        ),
    ]
